name: Checking

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - '.github/**'
      - '!.github/workflows/check.yml'

jobs:
  test_frontend:
    name: Frontend testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Set up Node.JS
        uses: actions/setup-node@v5
        with:
          node-version: 24

      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install frontend dependencies
        working-directory: ./src/frontend
        run: npm install

      - name: Install Playwright browsers
        working-directory: ./src/frontend
        run: npx playwright install --with-deps chromium

      - name: Frontend unit tests
        working-directory: ./src/frontend
        run: npm run test:unit

      - name: Frontend e2e tests
        working-directory: ./src/frontend
        run: npm run test:e2e
